### ISSUE TITLE
Scroll support option

### ISSUE THREAD

**Issue by chimon2000** [naderio/paper-select#4]
Being able to have scrolling after a certain number of items would be awesome.

Currently if there are 200 matching items, they are all displayed.

**Comment by naderio** [comment]
following global CSS should fix it
```css
paper-select::shadow paper-menu,
paper-select paper-menu {
  overflow-y: auto;
  max-height: 240px;
}
```
next release should have this fix
thanks!
